Adding support for Pocket
pokt-network/web-sdk pull request #2
Opened 2020-05-10 16:23 UTC by wgarcia4190

2020-05-11 17:13 UTC, luyzdeleon requested changes

2020-05-11 17:13 UTC, luyzdeleon commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
We need to remove this file @wgarcia4190

2020-05-11 17:13 UTC, luyzdeleon commented on packages/portis-eos/package-lock.json
>            "version": "2.1.1",
Why is this file changing?

2020-05-11 17:13 UTC, luyzdeleon commented on packages/portis-web3/src/index.ts
> +    if (this.pocket === undefined) {
How does this work?

2020-06-25 20:05 UTC, nymd approved these changes

2020-06-25 20:17 UTC, pabelnl approved these changes

2020-06-25 20:59 UTC, merged